# override the build pod images
jenkins:
  Agent:
    PodTemplates:
      Maven:
        Containers:
          Maven:
            Image: jenkinsxio/builder-maven:0.1.273
            RequestCpu: "0.5"
            RequestMemory: "2048Mi"
            LimitMemory: "2048Mi"
            LimitCpu: "1.5"
      Node10xWithCompose:
        Name: Node10xWithCompose
        Label: jenkins-node10x-with-compose
        volumes:
        - type: Secret
          secretName: jenkins-docker-cfg
          mountPath: /home/jenkins/.docker
        EnvVars:
          JENKINS_URL: http://jenkins:8080
          GIT_COMMITTER_EMAIL: jenkins-x@googlegroups.com
          GIT_AUTHOR_EMAIL: jenkins-x@googlegroups.com
          GIT_AUTHOR_NAME: jenkins-x-bot
          GIT_COMMITTER_NAME: jenkins-x-bot
          XDG_CONFIG_HOME: /home/jenkins
          DOCKER_CONFIG: /home/jenkins/.docker/
        ServiceAccount: jenkins
        Containers:
          Jnlp:
            Image: jenkinsci/jnlp-slave:3.14-1
            RequestCpu: "100m"
            RequestMemory: "128Mi"
            Args: '${computer.jnlpmac} ${computer.name}'
          Dlang:
            Image: msavy/jx-builder-nodejs10-compose:latest
            Privileged: true
            RequestCpu: "0.5"
            RequestMemory: "2048Mi"
            LimitCpu: "1.5"
            LimitMemory: "2048Mi"
            Command: "/bin/sh -c"
            Args: "cat"
            Tty: true